Repository dctafur/MISW4203-202312-Vinilos, pull requests merged in 2023-05, with the labels that each got.

#39 :sparkles: VN026: Listado de coleccionistas
  app/src/androidTest/java/com/vinyls/collectors/list/CollectorListTest.kt
  app/src/main/java/com/vinyls/collectors/CollectorModel.kt
  app/src/main/java/com/vinyls/collectors/CollectorRepository.kt
  app/src/main/java/com/vinyls/collectors/CollectorService.kt
  app/src/main/java/com/vinyls/collectors/CollectorsFragment.kt
  app/src/main/java/com/vinyls/collectors/CollectorsViewModel.kt
  app/src/main/java/com/vinyls/collectors/list/CollectorListAdapter.kt
  app/src/main/java/com/vinyls/collectors/list/CollectorListFragment.kt
  app/src/main/java/com/vinyls/collectors/list/CollectorListViewModel.kt
  app/src/main/res/layout/fragment_collector_item.xml
  app/src/main/res/layout/fragment_collector_list.xml
  app/src/main/res/layout/fragment_collectors.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: HU005, Sprint 1

#41 [VN010/feat] - Lista de Artistas
  app/src/androidTest/java/com/vinyls/performers/list/PerformerListTest.kt
  app/src/main/java/com/vinyls/performers/PerformerModel.kt
  app/src/main/java/com/vinyls/performers/PerformerRepository.kt
  app/src/main/java/com/vinyls/performers/PerformerService.kt
  app/src/main/java/com/vinyls/performers/PerformersFragment.kt
  app/src/main/java/com/vinyls/performers/PerformersViewModel.kt
  app/src/main/java/com/vinyls/performers/list/PerformerListAdapter.kt
  app/src/main/java/com/vinyls/performers/list/PerformerListFragment.kt
  app/src/main/java/com/vinyls/performers/list/PerformerListViewModel.kt
  app/src/main/res/layout/fragment_performer_item.xml
  app/src/main/res/layout/fragment_performer_list.xml
  app/src/main/res/layout/fragment_performers.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: HU003, Sprint 2

#42 [VN018/feat] - Vista para ver el detalle del coleccionista
  .gitignore
  app/src/androidTest/java/com/vinyls/albums/list/AlbumsListTest.kt
  app/src/androidTest/java/com/vinyls/collectors/list/CollectorListTest.kt
  app/src/main/java/com/vinyls/MainActivity.kt
  app/src/main/java/com/vinyls/albums/AlbumsService.kt
  app/src/main/java/com/vinyls/albums/list/AlbumsListFragment.kt
  app/src/main/java/com/vinyls/collectors/CollectorModel.kt
  app/src/main/java/com/vinyls/collectors/CollectorRepository.kt
  app/src/main/java/com/vinyls/collectors/CollectorsRepository.kt
  app/src/main/java/com/vinyls/collectors/CollectorsService.kt
  app/src/main/java/com/vinyls/collectors/details/CollectorsDetailsFragment.kt
  app/src/main/java/com/vinyls/collectors/details/CollectorsDetailsViewModel.kt
  app/src/main/java/com/vinyls/collectors/list/CollectorListFragment.kt
  app/src/main/java/com/vinyls/collectors/list/CollectorsListAdapter.kt
  app/src/main/java/com/vinyls/collectors/list/CollectorsListFragment.kt
  app/src/main/java/com/vinyls/collectors/list/CollectorsListViewModel.kt
  app/src/main/res/layout/fragment_album_item.xml
  app/src/main/res/layout/fragment_collectors_details.xml
  app/src/main/res/layout/fragment_collectors_list.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: HU006, Sprint 2

#43 [VN020/feat] - Implementar pruebas en vista para consultar el detalle de un coleccionista
  .idea/androidTestResultsUserPreferences.xml
  app/build.gradle
  app/src/androidTest/java/com/vinyls/collectors/details/CollectorsDetailsTest.kt
  app/src/androidTest/java/com/vinyls/collectors/list/CollectorListTest.kt
  app/src/androidTest/java/com/vinyls/performers/list/PerformerListTest.kt
  app/src/main/java/com/vinyls/collectors/details/CollectorsDetailsFragment.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_close_black_24dp.xml
  app/src/main/res/layout/fragment_collectors_details.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: HU006, Sprint 2

#45 [VN035/feat] - Reducir consumo de memoria y evitar ANRs
  app/src/main/java/com/vinyls/albums/AlbumsCacheManager.kt
  app/src/main/java/com/vinyls/albums/AlbumsRepository.kt
  app/src/main/java/com/vinyls/collectors/CollectorsCacheManager.kt
  app/src/main/java/com/vinyls/collectors/CollectorsRepository.kt
  app/src/main/java/com/vinyls/performers/PerformerRepository.kt
  app/src/main/java/com/vinyls/performers/PerformersCacheManager.kt
Labels: Sprint 2

#51 [VN036/fix] - Remove duplicated files
  .idea/androidTestResultsUserPreferences.xml
  app/src/main/java/com/vinyls/collectors/list/CollectorListAdapter.kt
  app/src/main/java/com/vinyls/collectors/list/CollectorListFragment.kt
  app/src/main/java/com/vinyls/collectors/list/CollectorListViewModel.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: bug

#52 [VN036/fix] - Remove duplicated files
  app/src/main/java/com/vinyls/collectors/list/CollectorListAdapter.kt
  app/src/main/java/com/vinyls/collectors/list/CollectorListFragment.kt
  app/src/main/java/com/vinyls/collectors/list/CollectorListViewModel.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: bug

#53 [VN037/fix] - Refactor code.
  .idea/androidTestResultsUserPreferences.xml
  app/build.gradle
  app/src/main/java/com/vinyls/MainActivity.kt
  app/src/main/java/com/vinyls/albums/AlbumsRepository.kt
  app/src/main/java/com/vinyls/albums/AlbumsService.kt
  app/src/main/java/com/vinyls/albums/create/AlbumCreateViewModel.kt
  app/src/main/java/com/vinyls/albums/create/AlbumsCreateFragment.kt
  app/src/main/java/com/vinyls/albums/list/AlbumsListFragment.kt
  app/src/main/java/com/vinyls/albums/list/AlbumsListViewModel.kt
  app/src/main/java/com/vinyls/collectors/CollectorRepository.kt
  app/src/main/java/com/vinyls/performers/PerformersFragment.kt
  app/src/main/java/com/vinyls/performers/PerformersRepository.kt
  app/src/main/java/com/vinyls/performers/PerformersService.kt
  app/src/main/java/com/vinyls/performers/PerformersViewModel.kt
  app/src/main/java/com/vinyls/performers/list/PerformersListAdapter.kt
  app/src/main/java/com/vinyls/performers/list/PerformersListFragment.kt
  app/src/main/java/com/vinyls/performers/list/PerformersListViewModel.kt
  app/src/main/res/drawable/ic_add_black_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_album_item.xml
  app/src/main/res/layout/fragment_albums_create.xml
  app/src/main/res/layout/fragment_albums_list.xml
  app/src/main/res/layout/fragment_collector_item.xml
  app/src/main/res/layout/fragment_collectors_details.xml
  app/src/main/res/layout/fragment_collectors_list.xml
  app/src/main/res/layout/fragment_performer_item.xml
  app/src/main/res/layout/fragment_performers.xml
  app/src/main/res/layout/fragment_performers_list.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: bug

#54 Hotfix/v1.0.3
  .idea/androidTestResultsUserPreferences.xml
  app/build.gradle
  app/src/main/java/com/vinyls/MainActivity.kt
  app/src/main/java/com/vinyls/albums/AlbumsRepository.kt
  app/src/main/java/com/vinyls/albums/AlbumsService.kt
  app/src/main/java/com/vinyls/albums/create/AlbumCreateFragment.kt
  app/src/main/java/com/vinyls/albums/create/AlbumCreateViewModel.kt
  app/src/main/java/com/vinyls/albums/create/AlbumsCreateFragment.kt
  app/src/main/java/com/vinyls/albums/create/AlbumsCreateViewModel.kt
  app/src/main/java/com/vinyls/albums/list/AlbumsListFragment.kt
  app/src/main/java/com/vinyls/albums/list/AlbumsListViewModel.kt
  app/src/main/java/com/vinyls/collectors/CollectorRepository.kt
  app/src/main/java/com/vinyls/collectors/details/CollectorsDetailsFragment.kt
  app/src/main/java/com/vinyls/performers/PerformerService.kt
  app/src/main/java/com/vinyls/performers/PerformersFragment.kt
  app/src/main/java/com/vinyls/performers/PerformersRepository.kt
  app/src/main/java/com/vinyls/performers/PerformersService.kt
  app/src/main/java/com/vinyls/performers/PerformersViewModel.kt
  app/src/main/java/com/vinyls/performers/list/PerformerListFragment.kt
  app/src/main/java/com/vinyls/performers/list/PerformersListAdapter.kt
  app/src/main/java/com/vinyls/performers/list/PerformersListFragment.kt
  app/src/main/java/com/vinyls/performers/list/PerformersListViewModel.kt
  app/src/main/res/drawable/ic_add_black_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_album_item.xml
  app/src/main/res/layout/fragment_albums_create.xml
  app/src/main/res/layout/fragment_albums_list.xml
  app/src/main/res/layout/fragment_collector_item.xml
  app/src/main/res/layout/fragment_collectors_details.xml
  app/src/main/res/layout/fragment_collectors_list.xml
  app/src/main/res/layout/fragment_performer_item.xml
  app/src/main/res/layout/fragment_performers.xml
  app/src/main/res/layout/fragment_performers_list.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: bug

#55 feat: add performer details view
  app/src/androidTest/java/com/vinyls/performers/details/PerformersDetailsTest.kt
  app/src/androidTest/java/com/vinyls/performers/list/PerformerListTest.kt
  app/src/main/java/com/vinyls/performers/PerformerModel.kt
  app/src/main/java/com/vinyls/performers/PerformersRepository.kt
  app/src/main/java/com/vinyls/performers/PerformersService.kt
  app/src/main/java/com/vinyls/performers/details/PerformersDetailsFragment.kt
  app/src/main/java/com/vinyls/performers/details/PerformersDetailsViewModel.kt
  app/src/main/java/com/vinyls/performers/list/PerformersListAdapter.kt
  app/src/main/java/com/vinyls/performers/list/PerformersListFragment.kt
  app/src/main/res/layout/fragment_performer_list.xml
  app/src/main/res/layout/fragment_performers_details.xml
  app/src/main/res/layout/fragment_performers_list.xml
Labels: HU004, Sprint 3

#57 [VN038/fix] - Actualizar la vista de detalles de un artista.
  app/src/main/java/com/vinyls/performers/details/PerformersDetailsFragment.kt
Labels: bug

#61 Fix/vn007 add to develop
  app/src/androidTest/java/com/vinyls/albums/list/AlbumsListTest.kt
  app/src/main/java/com/vinyls/albums/AlbumModel.kt
  app/src/main/java/com/vinyls/albums/AlbumsRepository.kt
  app/src/main/java/com/vinyls/albums/AlbumsService.kt
  app/src/main/java/com/vinyls/albums/create/AlbumsCreateFragment.kt
  app/src/main/java/com/vinyls/collectors/CollectorsRepository.kt
  app/src/main/java/com/vinyls/performers/PerformersRepository.kt
Labels: bug
